# Generated by Django 5.2.1 on 2026-06-28 08:44

import fernet_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0004_user_expiration_time_user_refresh_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='image_url',
            field=models.URLField(default='https://quequeue-user-uploads.s3.us-west-2.amazonaws.com/queue_covers/default.png'),
        ),
        migrations.AlterField(
            model_name='user',
            name='access_token',
            field=fernet_fields.fields.EncryptedCharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='refresh_token',
            field=fernet_fields.fields.EncryptedCharField(blank=True, max_length=500, null=True),
        ),
    ]
