# Generated by Django 5.2.7 on 2026-06-28 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0005_alter_queue_image_url_alter_user_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='share_token',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
