# Generated by Codex on 2026-06-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0005_alter_queue_image_url_alter_user_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='album_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='track',
            name='artist_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='track',
            name='popularity',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='release_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='spotify_track_id',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
    ]
