# Generated by Codex on 2026-06-28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0006_track_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueueRestoreJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('partial_failed', 'Partial failed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('total_tracks', models.PositiveIntegerField(default=0)),
                ('succeeded_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('failures', models.JSONField(blank=True, default=list)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restore_jobs', to='queues.queue')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restore_jobs', to='queues.user')),
            ],
        ),
    ]
