# Generated by Codex on 2026-06-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0007_queuerestorejob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='track_uri',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
