# Generated by integration on 2026-06-28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("queues", "0006_add_share_token"),
        ("queues", "0008_track_track_uri_index"),
    ]

    operations = []
