# docker-compose

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: quequeue_db
      POSTGRES_USER: quequeue_user
      POSTGRES_PASSWORD: quequeue_pass
    volumes:
      - pgdata:/var/lib/postgresql/data

  frontend:
    image: node:18  # official Node.js image
    working_dir: /app
    volumes:
      - ./quequeue-frontend:/app
      - /app/node_modules  # prevent node_modules overwrite
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev"
    depends_on:
      - web

volumes:
  pgdata:
