# Generated by Django 5.2.1 on 2025-05-18 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='image_url',
            field=models.URLField(default='https://example.com/default.jpg'),
        ),
    ]
