# Generated by Django 5.2.1 on 2025-05-19 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0002_queue_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
