# Generated by Django 5.2.1 on 2025-05-22 05:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0003_queue_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='expiration_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='user',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='queue',
            name='image_url',
            field=models.URLField(default='https://quequeue-user-uploads.s3.us-west-2.amazonaws.com/queue_covers/default.jpeg'),
        ),
    ]
