name: Deploy Frontend to S3

on:
  push:
    branches:
      - main
    paths:
      - "quequeue-frontend/**"

jobs:
  deploy:
    name: Build and Deploy Frontend
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: quequeue-frontend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: quequeue-frontend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build
        env:
            VITE_API_URL: ${{ secrets.VITE_API_URL }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Sync build to S3
        run: |
          aws s3 sync dist/ s3://${{ secrets.FRONTEND_S3_BUCKET }} \
            --delete \
            --cache-control "max-age=31536000,public"

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/*"
